# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 973b1386f241c092ab62b8f83f2d443f83830361ec864a84f7b2e30370a96c4ed5e56192dd707fe4d271efa49c3fe62a738878f3fc0b7cc4a3c0f8a6aa45ae17

test:
  secret_key_base: e104214db6640a84665a90b825b745b0826bab2ce5191e36c1092425c00fa64679fdb925c68bf5515f99b9a39041be5ffb5fec5be3334c9f6d793810386e8a51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
